export type Person = {
  nameCategory?: string;
  name: string;
  titleCode: string;
  M: number;
  "M/S": number;
  "M/S/C": number;
};

export const columnDataMustMid = [
  // "nameCategory",
  // "CategoryCode",
  "Name",
  "M",
  'M/S',
  'M/S/C',
]

// export const estimateResourceMustColumnDetails = [
//   {
//     header: 'Category',
//     accessorKey: 'nameCategory',
//     enableGrouping: true,
//   },
//   {
//     header: 'Name',
//     accessorKey: 'name',
//   },
//   {
//     header: 'M',
//     accessorKey: 'M',
//     isCalcultionEnabled: true,
//     aggregationFn: 'sum',
//     showBottomTotal: true,
//   },
//   {
//     header: 'M/S',
//     accessorKey: 'M/S',
//     isCalcultionEnabled: true,
//     aggregationFn: 'sum',
//     showBottomTotal: true,
//   },
//   {
//     header: 'M/S/C',
//     accessorKey: 'M/S/C',
//     isCalcultionEnabled: true,
//     aggregationFn: 'sum',
//     showBottomTotal: true,
//   },
// ]

export const estimateResourceMustColumnDetails = [
  {
    header: 'Category',
    accessorKey: 'nameCategory',
    enableGrouping: true,
  },
  {
    header: 'Name',
    accessorKey: 'name',
  },
  {
    header: '',
    accessorKey: 'M_Resource_Total',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
  {
    header: 'Resource 1',
    accessorKey: 'M_Resource1',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
  {
    header: 'Resource 2',
    accessorKey: 'M_Resource2',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
]

export const estimateResourceMustColumnDetailsHours = [
  {
    header: 'Category',
    accessorKey: 'nameCategory',
    enableGrouping: true,
  },
  {
    header: 'Name',
    accessorKey: 'name',
  },
  {
    header: '',
    accessorKey: 'M_Resource_Total',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
  {
    header: '',
    accessorKey: 'M_Resource_Total_H',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
  {
    header: 'Resource 1',
    accessorKey: 'M_Resource1',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
  {
    header: 'Resource 1 Hours',
    accessorKey: 'M_Resource1_H',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
  {
    header: 'Resource 2',
    accessorKey: 'M_Resource2',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
  {
    header: 'Resource 2 Hours',
    accessorKey: 'M_Resource2_H',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
]

export const estimateResourceMustShouldColumnDetails = [
  {
    header: 'Category',
    accessorKey: 'nameCategory',
    enableGrouping: true,
  },
  {
    header: 'Name',
    accessorKey: 'name',
  },
  {
    header: '',
    accessorKey: 'M/S_Resource_Total',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
  {
    header: 'Resource 1',
    accessorKey: 'M/S_Resource1',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
  {
    header: 'Resource 2',
    accessorKey: 'M/S_Resource2',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
]

export const estimateResourceMustShouldColumnDetailsHours = [
  {
    header: 'Category',
    accessorKey: 'nameCategory',
    enableGrouping: true,
  },
  {
    header: 'Name',
    accessorKey: 'name',
  },
  {
    header: '',
    accessorKey: 'M/S_Resource_Total',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
  {
    header: '',
    accessorKey: 'M/S_Resource_Total_H',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
  {
    header: 'Resource 1',
    accessorKey: 'M/S_Resource1',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
  {
    header: 'Resource 1 Hours',
    accessorKey: 'M/S_Resource1_H',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
  {
    header: 'Resource 2',
    accessorKey: 'M/S_Resource2',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
  {
    header: 'Resource 2 Hours',
    accessorKey: 'M/S_Resource2_H',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
]

export const estimateResourceMustShouldCouldColumnDetails = [
  {
    header: 'Category',
    accessorKey: 'nameCategory',
    enableGrouping: true,
  },
  {
    header: 'Name',
    accessorKey: 'name',
  },
  {
    header: '',
    accessorKey: 'M/S/C_Resource_Total',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
  {
    header: 'Resource 1',
    accessorKey: 'M/S/C_Resource1',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
  {
    header: 'Resource 2',
    accessorKey: 'M/S/C_Resource2',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
]

export const estimateResourceMustShouldCouldColumnDetailsHours = [
  {
    header: 'Category',
    accessorKey: 'nameCategory',
    enableGrouping: true,
  },
  {
    header: 'Name',
    accessorKey: 'name',
  },
  {
    header: '',
    accessorKey: 'M/S/C_Resource_Total',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
  {
    header: '',
    accessorKey: 'M/S/C_Resource_Total_H',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
  {
    header: 'Resource 1',
    accessorKey: 'M/S/C_Resource1',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
  {
    header: 'Resource 1 Hours',
    accessorKey: 'M/S/C_Resource1_H',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
  {
    header: 'Resource 2',
    accessorKey: 'M/S/C_Resource2',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
  {
    header: 'Resource 2 Hours',
    accessorKey: 'M/S/C_Resource2_H',
    isCalcultionEnabled: true,
    aggregationFn: 'sum',
    showBottomTotal: true,
  },
]

export const dataEstimateResource: any[] = [
  {
    "nameCategory": "ANALYSIS & DESIGN",
    name: 'Analysis and Design',
    titleCode: '1',
    'M_Resource_Total': 0,
    'M_Resource1': 0,
    'M_Resource2': 0,
    'M/S_Resource_Total': 0,
    'M/S_Resource1': 0,
    'M/S_Resource2': 0,
    'M/S/C_Resource_Total': 0,
    'M/S/C_Resource1': 0,
    'M/S/C_Resource2': 0,
    'M_Resource_Total_H': 0,
    'M_Resource1_H': 0,
    'M_Resource2_H': 0,
    'M/S_Resource_Total_H': 0,
    'M/S_Resource1_H': 0,
    'M/S_Resource2_H': 0,
    'M/S/C_Resource_Total_H': 0,
    'M/S/C_Resource1_H': 0,
    'M/S/C_Resource2_H': 0,	
    type: 'Estimate Resource'
  },
  {
    "nameCategory": "ANALYSIS & DESIGN",
    name: 'Customisations (Design)',
    titleCode: '1',
    'M_Resource_Total': 0,
    'M_Resource1': 0,
    'M_Resource2': 0,
    'M/S_Resource_Total': 0,
    'M/S_Resource1': 0,
    'M/S_Resource2': 0,
    'M/S/C_Resource_Total': 0,
    'M/S/C_Resource1': 0,
    'M/S/C_Resource2': 0,	
    'M_Resource_Total_H': 0,
    'M_Resource1_H': 0,
    'M_Resource2_H': 0,
    'M/S_Resource_Total_H': 0,
    'M/S_Resource1_H': 0,
    'M/S_Resource2_H': 0,
    'M/S/C_Resource_Total_H': 0,
    'M/S/C_Resource1_H': 0,
    'M/S/C_Resource2_H': 0,	
    type: 'Estimate Resource'
  },
  {
    "nameCategory": "ANALYSIS & DESIGN",
    name: 'Custom Requirements (Design)',
    titleCode: '1',
    'M_Resource_Total': 0,
    'M_Resource1': 0,
    'M_Resource2': 0,
    'M/S_Resource_Total': 0,
    'M/S_Resource1': 0,
    'M/S_Resource2': 0,
    'M/S/C_Resource_Total': 0,
    'M/S/C_Resource1': 0,
    'M/S/C_Resource2': 0,
    'M_Resource_Total_H': 0,
    'M_Resource1_H': 0,
    'M_Resource2_H': 0,
    'M/S_Resource_Total_H': 0,
    'M/S_Resource1_H': 0,
    'M/S_Resource2_H': 0,
    'M/S/C_Resource_Total_H': 0,
    'M/S/C_Resource1_H': 0,
    'M/S/C_Resource2_H': 0,	
    type: 'Estimate Resource'
  },
  {
    "nameCategory": "ANALYSIS & DESIGN",
    titleCode: '1',
    name: 'Documentation',
    'M_Resource_Total': 0,
    'M_Resource1': 0,
    'M_Resource2': 0,
    'M/S_Resource_Total': 0,
    'M/S_Resource1': 0,
    'M/S_Resource2': 0,
    'M/S/C_Resource_Total': 0,
    'M/S/C_Resource1': 0,
    'M/S/C_Resource2': 0,
    'M_Resource_Total_H': 0,
    'M_Resource1_H': 0,
    'M_Resource2_H': 0,
    'M/S_Resource_Total_H': 0,
    'M/S_Resource1_H': 0,
    'M/S_Resource2_H': 0,
    'M/S/C_Resource_Total_H': 0,
    'M/S/C_Resource1_H': 0,
    'M/S/C_Resource2_H': 0,	
    type: 'Estimate Resource'
  },
  {
    "nameCategory": "ANALYSIS & DESIGN",
    titleCode: '1',
    name: 'Design Review',
    'M_Resource_Total': 0,
    'M_Resource1': 0,
    'M_Resource2': 0,
    'M/S_Resource_Total': 0,
    'M/S_Resource1': 0,
    'M/S_Resource2': 0,
    'M/S/C_Resource_Total': 0,
    'M/S/C_Resource1': 0,
    'M/S/C_Resource2': 0,
    'M_Resource_Total_H': 0,
    'M_Resource1_H': 0,
    'M_Resource2_H': 0,
    'M/S_Resource_Total_H': 0,
    'M/S_Resource1_H': 0,
    'M/S_Resource2_H': 0,
    'M/S/C_Resource_Total_H': 0,
    'M/S/C_Resource1_H': 0,
    'M/S/C_Resource2_H': 0,	
    type: 'Estimate Resource'
  },
  {
    "nameCategory": "BUILD",
    titleCode: '2',
    name: 'Configuration',
    'M_Resource_Total': 0,
    'M_Resource1': 0,
    'M_Resource2': 0,
    'M/S_Resource_Total': 0,
    'M/S_Resource1': 0,
    'M/S_Resource2': 0,
    'M/S/C_Resource_Total': 0,
    'M/S/C_Resource1': 0,
    'M/S/C_Resource2': 0,
    'M_Resource_Total_H': 0,
    'M_Resource1_H': 0,
    'M_Resource2_H': 0,
    'M/S_Resource_Total_H': 0,
    'M/S_Resource1_H': 0,
    'M/S_Resource2_H': 0,
    'M/S/C_Resource_Total_H': 0,
    'M/S/C_Resource1_H': 0,
    'M/S/C_Resource2_H': 0,	
    type: 'Estimate Resource'
  },
  {
    "nameCategory": "BUILD",
    titleCode: '2',
    name: 'Integrations',
    'M_Resource_Total': 0,
    'M_Resource1': 0,
    'M_Resource2': 0,
    'M/S_Resource_Total': 0,
    'M/S_Resource1': 0,
    'M/S_Resource2': 0,
    'M/S/C_Resource_Total': 0,
    'M/S/C_Resource1': 0,
    'M/S/C_Resource2': 0,
    'M_Resource_Total_H': 0,
    'M_Resource1_H': 0,
    'M_Resource2_H': 0,
    'M/S_Resource_Total_H': 0,
    'M/S_Resource1_H': 0,
    'M/S_Resource2_H': 0,
    'M/S/C_Resource_Total_H': 0,
    'M/S/C_Resource1_H': 0,
    'M/S/C_Resource2_H': 0,	
    type: 'Estimate Resource'	
  },
  {
    "nameCategory": "BUILD",
    titleCode: '2',
    name: 'Customisations (Build)',
    'M_Resource_Total': 0,
    'M_Resource1': 0,
    'M_Resource2': 0,
    'M/S_Resource_Total': 0,
    'M/S_Resource1': 0,
    'M/S_Resource2': 0,
    'M/S/C_Resource_Total': 0,
    'M/S/C_Resource1': 0,
    'M/S/C_Resource2': 0,
    'M_Resource_Total_H': 0,
    'M_Resource1_H': 0,
    'M_Resource2_H': 0,
    'M/S_Resource_Total_H': 0,
    'M/S_Resource1_H': 0,
    'M/S_Resource2_H': 0,
    'M/S/C_Resource_Total_H': 0,
    'M/S/C_Resource1_H': 0,
    'M/S/C_Resource2_H': 0,	
    type: 'Estimate Resource'
  },
  {
    "nameCategory": "BUILD",
    titleCode: '2',
    name: 'Custom Requirements (Build)',
    'M_Resource_Total': 0,
    'M_Resource1': 0,
    'M_Resource2': 0,
    'M/S_Resource_Total': 0,
    'M/S_Resource1': 0,
    'M/S_Resource2': 0,
    'M/S/C_Resource_Total': 0,
    'M/S/C_Resource1': 0,
    'M/S/C_Resource2': 0,	
    'M_Resource_Total_H': 0,
    'M_Resource1_H': 0,
    'M_Resource2_H': 0,
    'M/S_Resource_Total_H': 0,
    'M/S_Resource1_H': 0,
    'M/S_Resource2_H': 0,
    'M/S/C_Resource_Total_H': 0,
    'M/S/C_Resource1_H': 0,
    'M/S/C_Resource2_H': 0,	
    type: 'Estimate Resource'	
  },
  {
    "nameCategory": "BUILD",
    titleCode: '2',
    name: 'Document Layouts',
    'M_Resource_Total': 0,
    'M_Resource1': 0,
    'M_Resource2': 0,
    'M/S_Resource_Total': 0,
    'M/S_Resource1': 0,
    'M/S_Resource2': 0,
    'M/S/C_Resource_Total': 0,
    'M/S/C_Resource1': 0,
    'M/S/C_Resource2': 0,	
    'M_Resource_Total_H': 0,
    'M_Resource1_H': 0,
    'M_Resource2_H': 0,
    'M/S_Resource_Total_H': 0,
    'M/S_Resource1_H': 0,
    'M/S_Resource2_H': 0,
    'M/S/C_Resource_Total_H': 0,
    'M/S/C_Resource1_H': 0,
    'M/S/C_Resource2_H': 0,	
    type: 'Estimate Resource'
  },
  {
    "nameCategory": "BUILD",
    titleCode: '2',
    name: 'Reporting',
    'M_Resource_Total': 0,
    'M_Resource1': 0,
    'M_Resource2': 0,
    'M/S_Resource_Total': 0,
    'M/S_Resource1': 0,
    'M/S_Resource2': 0,
    'M/S/C_Resource_Total': 0,
    'M/S/C_Resource1': 0,
    'M/S/C_Resource2': 0,	
    'M_Resource_Total_H': 0,
    'M_Resource1_H': 0,
    'M_Resource2_H': 0,
    'M/S_Resource_Total_H': 0,
    'M/S_Resource1_H': 0,
    'M/S_Resource2_H': 0,
    'M/S/C_Resource_Total_H': 0,
    'M/S/C_Resource1_H': 0,
    'M/S/C_Resource2_H': 0,	
    type: 'Estimate Resource'
  },
  {
    "nameCategory": "BUILD",
    titleCode: '2',
    name: 'Data Migration',
    'M_Resource_Total': 0,
    'M_Resource1': 0,
    'M_Resource2': 0,
    'M/S_Resource_Total': 0,
    'M/S_Resource1': 0,
    'M/S_Resource2': 0,
    'M/S/C_Resource_Total': 0,
    'M/S/C_Resource1': 0,
    'M/S/C_Resource2': 0,	
    'M_Resource_Total_H': 0,
    'M_Resource1_H': 0,
    'M_Resource2_H': 0,
    'M/S_Resource_Total_H': 0,
    'M/S_Resource1_H': 0,
    'M/S_Resource2_H': 0,
    'M/S/C_Resource_Total_H': 0,
    'M/S/C_Resource1_H': 0,
    'M/S/C_Resource2_H': 0,	
    type: 'Estimate Resource'
  },
  {
    "nameCategory": "BUILD",
    titleCode: '2',
    name: 'CRP',
    'M_Resource_Total': 0,
    'M_Resource1': 0,
    'M_Resource2': 0,
    'M/S_Resource_Total': 0,
    'M/S_Resource1': 0,
    'M/S_Resource2': 0,
    'M/S/C_Resource_Total': 0,
    'M/S/C_Resource1': 0,
    'M/S/C_Resource2': 0,
    'M_Resource_Total_H': 0,
    'M_Resource1_H': 0,
    'M_Resource2_H': 0,
    'M/S_Resource_Total_H': 0,
    'M/S_Resource1_H': 0,
    'M/S_Resource2_H': 0,
    'M/S/C_Resource_Total_H': 0,
    'M/S/C_Resource1_H': 0,
    'M/S/C_Resource2_H': 0,	
    type: 'Estimate Resource'
  },
  {
    "nameCategory": "BUILD",
    titleCode: '2',
    name: 'Testing',
    'M_Resource_Total': 0,
    'M_Resource1': 0,
    'M_Resource2': 0,
    'M/S_Resource_Total': 0,
    'M/S_Resource1': 0,
    'M/S_Resource2': 0,
    'M/S/C_Resource_Total': 0,
    'M/S/C_Resource1': 0,
    'M/S/C_Resource2': 0,
    'M_Resource_Total_H': 0,
    'M_Resource1_H': 0,
    'M_Resource2_H': 0,
    'M/S_Resource_Total_H': 0,
    'M/S_Resource1_H': 0,
    'M/S_Resource2_H': 0,
    'M/S/C_Resource_Total_H': 0,
    'M/S/C_Resource1_H': 0,
    'M/S/C_Resource2_H': 0,	
    type: 'Estimate Resource'	
  },
  {
    "nameCategory": "DEPLOY",
    titleCode: '3',
    name: 'Train-the-trainer',
    'M_Resource_Total': 0,
    'M_Resource1': 0,
    'M_Resource2': 0,
    'M/S_Resource_Total': 0,
    'M/S_Resource1': 0,
    'M/S_Resource2': 0,
    'M/S/C_Resource_Total': 0,
    'M/S/C_Resource1': 0,
    'M/S/C_Resource2': 0,	
    'M_Resource_Total_H': 0,
    'M_Resource1_H': 0,
    'M_Resource2_H': 0,
    'M/S_Resource_Total_H': 0,
    'M/S_Resource1_H': 0,
    'M/S_Resource2_H': 0,
    'M/S/C_Resource_Total_H': 0,
    'M/S/C_Resource1_H': 0,
    'M/S/C_Resource2_H': 0,	
    type: 'Estimate Resource'
  },
  {
    "nameCategory": "DEPLOY",
    titleCode: '3',
    name: 'UAT Environment Preparation',
    'M_Resource_Total': 0,
    'M_Resource1': 0,
    'M_Resource2': 0,
    'M/S_Resource_Total': 0,
    'M/S_Resource1': 0,
    'M/S_Resource2': 0,
    'M/S/C_Resource_Total': 0,
    'M/S/C_Resource1': 0,
    'M/S/C_Resource2': 0,	
    'M_Resource_Total_H': 0,
    'M_Resource1_H': 0,
    'M_Resource2_H': 0,
    'M/S_Resource_Total_H': 0,
    'M/S_Resource1_H': 0,
    'M/S_Resource2_H': 0,
    'M/S/C_Resource_Total_H': 0,
    'M/S/C_Resource1_H': 0,
    'M/S/C_Resource2_H': 0,	
    type: 'Estimate Resource'
  },
  {
    "nameCategory": "DEPLOY",
    titleCode: '3',
    name: 'UAT Support',
    'M_Resource_Total': 0,
    'M_Resource1': 0,
    'M_Resource2': 0,
    'M/S_Resource_Total': 0,
    'M/S_Resource1': 0,
    'M/S_Resource2': 0,
    'M/S/C_Resource_Total': 0,
    'M/S/C_Resource1': 0,
    'M/S/C_Resource2': 0,	
    'M_Resource_Total_H': 0,
    'M_Resource1_H': 0,
    'M_Resource2_H': 0,
    'M/S_Resource_Total_H': 0,
    'M/S_Resource1_H': 0,
    'M/S_Resource2_H': 0,
    'M/S/C_Resource_Total_H': 0,
    'M/S/C_Resource1_H': 0,
    'M/S/C_Resource2_H': 0,	
    type: 'Estimate Resource'
  },
  {
    "nameCategory": "DEPLOY",
    titleCode: '3',
    name: 'PROD Environment Preparation',
    'M_Resource_Total': 0,
    'M_Resource1': 0,
    'M_Resource2': 0,
    'M/S_Resource_Total': 0,
    'M/S_Resource1': 0,
    'M/S_Resource2': 0,
    'M/S/C_Resource_Total': 0,
    'M/S/C_Resource1': 0,
    'M/S/C_Resource2': 0,	
    'M_Resource_Total_H': 0,
    'M_Resource1_H': 0,
    'M_Resource2_H': 0,
    'M/S_Resource_Total_H': 0,
    'M/S_Resource1_H': 0,
    'M/S_Resource2_H': 0,
    'M/S/C_Resource_Total_H': 0,
    'M/S/C_Resource1_H': 0,
    'M/S/C_Resource2_H': 0,	
    type: 'Estimate Resource'
  },
  {
    "nameCategory": "DEPLOY",
    titleCode: '3',
    name: 'Support Handover',
    'M_Resource_Total': 0,
    'M_Resource1': 0,
    'M_Resource2': 0,
    'M/S_Resource_Total': 0,
    'M/S_Resource1': 0,
    'M/S_Resource2': 0,
    'M/S/C_Resource_Total': 0,
    'M/S/C_Resource1': 0,
    'M/S/C_Resource2': 0,	
    'M_Resource_Total_H': 0,
    'M_Resource1_H': 0,
    'M_Resource2_H': 0,
    'M/S_Resource_Total_H': 0,
    'M/S_Resource1_H': 0,
    'M/S_Resource2_H': 0,
    'M/S/C_Resource_Total_H': 0,
    'M/S/C_Resource1_H': 0,
    'M/S/C_Resource2_H': 0,	
    type: 'Estimate Resource'	
  },
  {
    "nameCategory": "OPERATION",
    titleCode: '4',
    name: 'End user training',
    'M_Resource_Total': 0,
    'M_Resource1': 0,
    'M_Resource2': 0,
    'M/S_Resource_Total': 0,
    'M/S_Resource1': 0,
    'M/S_Resource2': 0,
    'M/S/C_Resource_Total': 0,
    'M/S/C_Resource1': 0,
    'M/S/C_Resource2': 0,	
    'M_Resource_Total_H': 0,
    'M_Resource1_H': 0,
    'M_Resource2_H': 0,
    'M/S_Resource_Total_H': 0,
    'M/S_Resource1_H': 0,
    'M/S_Resource2_H': 0,
    'M/S/C_Resource_Total_H': 0,
    'M/S/C_Resource1_H': 0,
    'M/S/C_Resource2_H': 0,	
    type: 'Estimate Resource'
  },
  {
    "nameCategory": "OPERATION",
    titleCode: '4',
    name: 'Post Go-Live Support',
    'M_Resource_Total': 0,
    'M_Resource1': 0,
    'M_Resource2': 0,
    'M/S_Resource_Total': 0,
    'M/S_Resource1': 0,
    'M/S_Resource2': 0,
    'M/S/C_Resource_Total': 0,
    'M/S/C_Resource1': 0,
    'M/S/C_Resource2': 0,	
    'M_Resource_Total_H': 0,
    'M_Resource1_H': 0,
    'M_Resource2_H': 0,
    'M/S_Resource_Total_H': 0,
    'M/S_Resource1_H': 0,
    'M/S_Resource2_H': 0,
    'M/S/C_Resource_Total_H': 0,
    'M/S/C_Resource1_H': 0,
    'M/S/C_Resource2_H': 0,	
    type: 'Estimate Resource'
  },
  // {
  //   "nameCategory": undefined,
  //   titleCode: '5',
  //   name: 'Sub Total',
  //   M: 0,
  //   'M/S': 0,
  //   'M/S/C': 0	
  // },
  // {
  //   "nameCategory": undefined,
  //   titleCode: '6',
  //   name: 'Project Manager',
  //   M: 0,
  //   'M/S': 0,
  //   'M/S/C': 0	
  // },
  // {
  //   "nameCategory": undefined,
  //   titleCode: '7',
  //   name: 'Project Risk',
  //   M: 0,
  //   'M/S': 0,
  //   'M/S/C': 0	
  // },
  {
    "nameCategory": 'Sub Total',
    titleCode: '5',
    name: '',
    'M_Resource_Total': 0,
    'M_Resource1': 0,
    'M_Resource2': 0,
    'M/S_Resource_Total': 0,
    'M/S_Resource1': 0,
    'M/S_Resource2': 0,
    'M/S/C_Resource_Total': 0,
    'M/S/C_Resource1': 0,
    'M/S/C_Resource2': 0,	
    'M_Resource_Total_H': 0,
    'M_Resource1_H': 0,
    'M_Resource2_H': 0,
    'M/S_Resource_Total_H': 0,
    'M/S_Resource1_H': 0,
    'M/S_Resource2_H': 0,
    'M/S/C_Resource_Total_H': 0,
    'M/S/C_Resource1_H': 0,
    'M/S/C_Resource2_H': 0,	
    type: 'Estimate Resource'
  },
  {
    "nameCategory": 'Project Manager',
    titleCode: '6',
    name: '',
    'M_Resource_Total': 0,
    'M_Resource1': 0,
    'M_Resource2': 0,
    'M/S_Resource_Total': 0,
    'M/S_Resource1': 0,
    'M/S_Resource2': 0,
    'M/S/C_Resource_Total': 0,
    'M/S/C_Resource1': 0,
    'M/S/C_Resource2': 0,	
    'M_Resource_Total_H': 0,
    'M_Resource1_H': 0,
    'M_Resource2_H': 0,
    'M/S_Resource_Total_H': 0,
    'M/S_Resource1_H': 0,
    'M/S_Resource2_H': 0,
    'M/S/C_Resource_Total_H': 0,
    'M/S/C_Resource1_H': 0,
    'M/S/C_Resource2_H': 0,	
    type: 'Estimate Resource'
  },
  {
    "nameCategory": 'Project Risk',
    titleCode: '7',
    name: '',
    'M_Resource_Total': 0,
    'M_Resource1': 0,
    'M_Resource2': 0,
    'M/S_Resource_Total': 0,
    'M/S_Resource1': 0,
    'M/S_Resource2': 0,
    'M/S/C_Resource_Total': 0,
    'M/S/C_Resource1': 0,
    'M/S/C_Resource2': 0,
    'M_Resource_Total_H': 0,
    'M_Resource1_H': 0,
    'M_Resource2_H': 0,
    'M/S_Resource_Total_H': 0,
    'M/S_Resource1_H': 0,
    'M/S_Resource2_H': 0,
    'M/S/C_Resource_Total_H': 0,
    'M/S/C_Resource1_H': 0,
    'M/S/C_Resource2_H': 0,		
    type: 'Estimate Resource'
  },
  // {
  //   "nameCategory": ' ',
  //   titleCode: '8',
  //   name: 'Total',
  //   M: 0,
  //   'M/S': 0,
  //   'M/S/C': 0	
  // },
];
